DZE_CLICK_ACTIONS = [
    ["ItemKnife","Colher Erva","execVM 'custom\weed\hemp.sqf';","true"],
    ["ItemMachete","Colher Erva","execVM 'custom\weed\hemp.sqf';","true"],
    ["ItemKiloHemp","Smoke Weed","execVM 'custom\weed\smoke.sqf';","true"],
    ["ItemToolbox","Montar Bike","execVM 'custom\Menu\scripts\deploy.sqf';","true"],
    ["ItemToolbox","Montar Moto","['TT650_Civ'] execVM 'custom\EVD\EVD_deploy.sqf';","true"],
    ["ItemToolbox","Montar Mozzie","['CSJ_GyroC'] execVM 'custom\EVD\EVD_deploy.sqf';","true"],
	["ItemToolbox","Fazer Faca","[] execVM 'overwrites\click_actions\examples\makeknife.sqf';","true"],
	["ItemToolbox","Fazer CrossBow","[] execVM 'overwrites\click_actions\examples\makebow.sqf';","true"],
	["ItemToolbox","Fazer CinderBlocks","[] execVM 'overwrites\click_actions\examples\makecinderblock.sqf';","true"],
    ["ItemRadio","Gerenciar Grupo","execVM 'addons\dzgm\loadGroupManagement.sqf';","true"],
    ["ItemRadio","Chamar Evac-Chopper","execVM 'custom\JAEM\CallEvacChopper.sqf';","true"],
    ["ItemRadio","ON/OFF","execVM 'custom\switch_on_off.sqf';","true"],
    ["ItemBriefcase_Base","Abrir Maleta Premium","execVM 'addons\mbc\open_brief.sqf';","true"],
    ["ItemSilvercase_Base","Abrir Maleta Bronze","execVM 'addons\mbc\open_silver.sqf';","true"],
	["ItemKnife","Fazer Flechas","[] execVM 'overwrites\click_actions\examples\makearrow.sqf';","true"],
	["ItemKnife","Fazer Bandage","[] execVM 'overwrites\click_actions\examples\makebandage.sqf';","true"],
	["ItemBriefcase100oz","Pedir Suprimentos","[] execVM 'scripts\Carepackage\carepackage.sqf';","true"],
	["ItemBriefcase100oz","Pedir Suprimentos(No Mapa)","[] execVM 'scripts\Carepackage2\clickpackage.sqf';","true"],
    ["ItemMap","Informacoes","execVM 'overwrites\click_actions\examples\info.sqf';","true"],
    ["ItemMap","Guia de Construcao","execVM 'overwrites\click_actions\examples\craft.sqf';","true"],
    ["ItemMap","Craft Items Epoch Pt1","execVM 'overwrites\click_actions\examples\epoch.sqf';","true"],
    ["ItemMap","Craft Items Epoch Pt2","execVM 'overwrites\click_actions\examples\epoch2.sqf';","true"],
    ["ItemMap","Craft Items Epoch Pt3","execVM 'overwrites\click_actions\examples\epoch3.sqf';","true"],
    ["ItemMap","Construcoes Epoch Pt1","execVM 'overwrites\click_actions\examples\epoch4.sqf';","true"],
    ["ItemMap","Construcoes Epoch Pt2","execVM 'overwrites\click_actions\examples\epoch5.sqf';","true"],
    ["ItemMap","Construcoes Epoch Pt3","execVM 'overwrites\click_actions\examples\epoch6.sqf';","true"],
    ["Binocular_Vector","500 Metros","setViewDistance 500; systemChat('Distancia: 500'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular_Vector","1000 Metros","setViewDistance 1000; systemChat('Distancia: 1000'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular_Vector","1500 Metros","setViewDistance 1500; systemChat('Distancia: 1500'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular_Vector","2000 Metros","setViewDistance 2000; systemChat('Distancia: 2000'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular_Vector","2500 Metros","setViewDistance 2500; systemChat('Distancia: 2500'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular_Vector","3000 Metros","setViewDistance 3000; systemChat('Distancia: 3000'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular_Vector","4000 Metros","setViewDistance 4000; systemChat('Distancia: 4000'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular_Vector","5000 Metros","setViewDistance 5000; systemChat('Distancia: 5000'); systemChat('Aviso: Lag mode ON');","true"],
    ["Binocular","500 Metros","setViewDistance 500; systemChat('Distancia: 500'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular","1000 Metros","setViewDistance 1000; systemChat('Distancia: 1000'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular","1500 Metros","setViewDistance 1500; systemChat('Distancia: 1500'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular","2000 Metros","setViewDistance 2000; systemChat('Distancia: 2000'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular","2500 Metros","setViewDistance 2500; systemChat('Distancia: 2500'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular","3000 Metros","setViewDistance 3000; systemChat('Distancia: 3000'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular","4000 Metros","setViewDistance 4000; systemChat('Distancia: 4000'); systemChat('Aviso: Distancias muito altas podem diminuir o FPS');","true"],
    ["Binocular","5000 Metros","setViewDistance 5000; systemChat('Distancia: 5000'); systemChat('Aviso: Lag mode ON');","true"]
];